#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
