#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/powerpuffgirl.tech/html/index.html
sudo service nginx start
