#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello world!" | sudo tee /var/www/html/index.html
sudo service nginx start
