#!/usr/bin/env bash
# Not found page 404

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start 
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
printf %s "server {
        listen 80 default server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        
        error_page 404 /404.html;
        location /404 {
                root  /var/www/html;
                internal;
        }
}
" > etc /etc/nginx/sites-available/default
service nginx start
