#!/usr/bin/env bash
# configuration of web-02 to be identical with web-01, ngix header addition
sudo apt-get update -y
sudo apt-get install nginx -y
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
