#!/usr/in/env bash
# HaProxy installation and configuartion

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install haproxy=2.6.\*
echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back\n
        
        backend http_back
          balance roundrobin
          server 13294-web-01 3.229.120.108:80 check
          server 13294-web-02 44.210.236.132:80 check"
 | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
