#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server, active IPv4 IPs
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
