#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntucontainer’s Nginx installation from listening on port 80.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
