#!/usr/vin/python3
# Using what you did for task #0, make your fix short and sweet.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/defaul
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
