#!/usr/bin/env bash

# Bash script that displays Best School 10 times.
# use the while loop (for and until are forbidden)

COUNTER=0
while [ "$COUNTER" -lt 10 ];
do
	echo "Best School"
	let COUNTER=COUNTER+1
done
