#!/usr/bin/env bash

# Bash script that displays Best School 10 times.
# use the while loop (for and until are forbidden)

Count=0
while [ "$Count" -le 10 ]
do
	echo "Best School"
	let count=Count+1
done
