#!/usr/bin/env bash

# Bash script that displays: The content of the current directory, In a list format, 
# Where only the part of the name after the first dash is displayed (refer to the example)
# use the for loop (while and until are forbidden)
# Do not display hidden files

for k in *;
do
	echo "$k" | cut -d'-' -f2
done
