#!/usr/bin/env bash
# a Bash script that listens on port 98 on localhost.
# sudo ./100-port_listening_on_localhost - Starting my script.
# telnet localhost 98 - Connecting to localhost on port 98 using,
# telnet and typing some text.

nc -l 98
